version: 2
jobs:
  build:
    working_directory: ~/headstart
    docker:
      - image: circleci/node:6.10
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: fix-readable-stream
          command: 'sudo npm i -g process-nextick-args util-deprecate'
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm test
