version: 2
jobs:
  build:
    working_directory: ~/headstart
    docker:
      - image: circleci/node:7
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm test
